apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  KAFKA_BOOTSTRAP: "helep-kafka-bootstrap.kafka.svc.cluster.local:9092"
  MATCHER: "nearest"
  DB_PATH: "/data/user.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sos-service-config
data:
  KAFKA_BOOTSTRAP: "helep-kafka-bootstrap.kafka.svc.cluster.local:9092"
  DB_PATH: "/data/sos.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dispatch-service-config
data:
  KAFKA_BOOTSTRAP: "helep-kafka-bootstrap.kafka.svc.cluster.local:9092"
  MATCHER: "nearest"
  DB_PATH: "/data/dispatch.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  KAFKA_BOOTSTRAP: "helep-kafka-bootstrap.kafka.svc.cluster.local:9092"
  DB_PATH: "/data/notification.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
data:
  KAFKA_BOOTSTRAP: "helep-kafka-bootstrap.kafka.svc.cluster.local:9092"
  DB_PATH: "/data/analytics.db"