apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helep-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: helep.local
      http:
        paths:
          - path: /user
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8001
          - path: /sos
            pathType: Prefix
            backend:
              service:
                name: sos-service
                port:
                  number: 8002
          - path: /analytics
            pathType: Prefix
            backend:
              service:
                name: analytics-service
                port:
                  number: 8005